### ISSUE TITLE
Debug and document - Initialization Error on RStudio server

### ISSUE THREAD

**Issue by Maddocent** [uashogeschoolutrecht/docs-hpc#2]
Problem: Could not login to the dartpaths-20 Rstudio server after working in personal account on the server. 
Fixed it with:

Deleting: 
 
 - active sessions in user-account `~/.rstudio/active`
 - deleting `~/.rstudio` folder

After this user could login but session kept on crashing every time RStudio project was openend
Fixed it with:

 Deleting:

 - `~/R` in user home folder

**Comment by ikhoury** [comment]
Docs available at https://datascience.hu.nl/docs/rstudio/faq/
