### ISSUE TITLE
Add Manual on how to enable SSH access to HU-VRE RStudio Server workspace

### ISSUE THREAD

**Issue by Maddocent** [uashogeschoolutrecht/docs-hpc#3]
In order to allow users to SSH directly into the server. Ad documentation on: 

 - Generate SSH public private key pair on local machine
 - Add public key to server
 - Activate use of private key and the connection
 - Store details of workspace connection in ssh config file to enable ssh into machine by using alias

**Comment by ikhoury** [comment]
Docs available at https://datascience.hu.nl/docs/faq/
